var equipments=[
    {
        equipmentsName:'百万分之一水平仪',
        equipmentsId:"2sws6erta6s7328ds3"
    },
    {
        equipmentsName:'超纯水系统',
        equipmentsId:"2swswewe324rtr343"
    },
     {
        equipmentsName:'超高压气体吸附仪',
        equipmentsId:"52323sd43434ewevt"
    },
     {
        equipmentsName:'电感偶合仪',
        equipmentsId:"8sdh3434u656u8ds3"
    },
     {
        equipmentsName:'电化学工作站',
        equipmentsId:"90ewurerie44sds333"
    },
     {
        equipmentsName:'电化学综合检测仪',
        equipmentsId:"uiu232is253322sdsd"
    },
     {
        equipmentsName:'傅里叶红外线',
        equipmentsId:"78ewe7we343uwe8u8w"
    },
     {
        equipmentsName:'环境微生物分子',
        equipmentsId:"d7f6f4h54de54g673r"
    },
     {
        equipmentsName:'化学吸附仪',
        equipmentsId:"s7sdhu3437dy8e8f9"
    },
     {
        equipmentsName:'Evroment设备',
        equipmentsId:"23rt73df2ytt8ds3"
    },
     {
        equipmentsName:'火焰原子吸收',
        equipmentsId:"0jfu456ru43ty435"
    },
     {
        equipmentsName:'气相色谱-质谱仪',
        equipmentsId:"2s090j434rt454trta"
    },
     {
        equipmentsName:'气相色谱仪',
        equipmentsId:"74ui837de485rt43423"
    },
     {
        equipmentsName:'全自动洗衣机',
        equipmentsId:"28fh77rrht93435s3"
    },
     {
        equipmentsName:'热重分析仪',
        equipmentsId:"9023frtr43u55gt7n"
    },
     {
        equipmentsName:'双恒电位设备',
        equipmentsId:"wew7434feere98fr9"
    },{
        equipmentsName:'微波消解',
        equipmentsId:"wew64rf8i9ere9"
    },{
        equipmentsName:'X-射线',
        equipmentsId:"wew7434feere98fr9"
    },{
        equipmentsName:'显微镜',
        equipmentsId:"we34rtry324erre"
    },{
        equipmentsName:'旋转留变异',
        equipmentsId:"wew7434feere98fr9"
    },{
        equipmentsName:'油浓度设备',
        equipmentsId:"wew2839errty2897sd8f"
    },{
        equipmentsName:'元素分析仪',
        equipmentsId:"wew2w343eweere98fr9"
    }
]